# Generated by Django 3.0.8 on 2021-02-27 11:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('domain', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, default='', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_email_active', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=250)),
                ('student', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('reg_link', models.CharField(max_length=2000)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2021, 2, 27, 11, 21, 45, 19179, tzinfo=utc))),
                ('time', models.TimeField(blank=True, default='20:00')),
                ('duration', models.IntegerField(blank=True, default=0)),
                ('medium', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
                ('rules_pdf', models.FileField(blank=True, upload_to='uploads/')),
                ('syllabus_pdf', models.FileField(blank=True, upload_to='uploads/')),
                ('marking_scheme', models.FileField(blank=True, upload_to='uploads/')),
                ('extra_details', models.CharField(blank=True, max_length=2000)),
                ('is_govt', models.BooleanField(default=False)),
                ('last_day_register', models.DateField(default=datetime.datetime(2021, 2, 27, 11, 21, 45, 19856, tzinfo=utc))),
                ('degree', models.CharField(default='-', max_length=20)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Institute')),
                ('student', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
