# Generated by Django 3.0.8 on 2021-02-27 22:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 27, 22, 21, 27, 214922, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='last_day_register',
            field=models.DateField(default=datetime.datetime(2021, 2, 27, 22, 21, 27, 215166, tzinfo=utc)),
        ),
    ]
