# Generated by Django 3.0.8 on 2021-02-27 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210227_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='youtube_link2',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 27, 22, 57, 9, 404116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='last_day_register',
            field=models.DateField(default=datetime.datetime(2021, 2, 27, 22, 57, 9, 404371, tzinfo=utc)),
        ),
    ]
