# Generated by Django 3.0.8 on 2021-02-27 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210227_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 27, 22, 57, 14, 202240, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='last_day_register',
            field=models.DateField(default=datetime.datetime(2021, 2, 27, 22, 57, 14, 202494, tzinfo=utc)),
        ),
    ]
